version: "3.5"

services:
  nginx:
    container_name: amazon-app
    build:
      context: ./docker-image/nginx/
    ports:
      - 3000:80
    volumes:
      - ./var/www/html:/var/www/html/
      - ./docker-image/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-image/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-image/nginx/conf.d:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx/
    depends_on:
      - phpfpm
      - mysql

  phpfpm:
    container_name: amazon-php
    build:
      context: ./docker-image/php/
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./var/www/html:/var/www/html/
      - ./log/php-fpm:/var/log/php-fpm
      - ./docker-image/php/php-fpm.d:/etc/php-fpm.d/
    ports:
      - 9000:80

  mysql:
    hostname: amazon-db
    container_name: amazon-db
    build:
      context: ./docker-image/mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker

  phpmyadmin:
    hostname: amazon-pma
    container_name: amazon-pma
    build:
      context: ./docker-image/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - /sessions
