version: "3"

services:
  web:
    hostname: amazon-app
    container_name: amazon-app
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      #- ./code:/code
      - ./var/www:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  php:
    hostname: amazon-php
    container_name: amazon-php
    build: ./php
    volumes:
      #- ./code:/code
      - ./var/www:/var/www

  mysql:
    hostname: amazon-db
    container_name: amazon-db
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker

  phpmyadmin:
    hostname: amazon-pma
    container_name: amazon-pma
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - /sessions
